manifest:
  remotes:
    - name: remote-name
      url-base: https://github.com/Topher083/zmk-nice-view-custom
  projects:
    # Together with the above defined remote, this refers to a module located at
    # https://github.com/remote-name/repository-name
    - name: zmk-nice-view-custom
      remote: remote-name
      # This points to a west manifest file in the remote module for further imports
      import: west.yml
